[package]
name = "perfetto-cupti-gpu-compute"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[workspace]
members = ["cupti-profiler", "cupti-profiler-sys"]

[dependencies]
cupti-profiler = { path = "./cupti-profiler" }
cpp_demangle = "0.5"
libc = "0.2"
once_cell = "1.18"
perfetto-sdk = "0.1"
perfetto-sdk-protos-gpu = "0.1"

[features]
stubs = ["cupti-profiler/stubs"]
