[package]
name = "cupti-profiler-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.2.51"
bindgen = { version = "0.69", optional = true }

[features]
stubs = []
gen = ["dep:bindgen"]
