[package]
name = "cupti-profiler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
libc = "0.2"
cupti-profiler-sys = { path = "../cupti-profiler-sys" }

[features]
stubs = ["cupti-profiler-sys/stubs"]
